backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "articles"
    label: "Artikel"
    folder: "src/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Bild", name: "image", widget: "image", required: false, default: "/placeholder.png" }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false, default: "placeholder" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["articles"] }
  - name: "category"
    label: "Kategorie"
    folder: "src/category"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Bild", name: "image", widget: "image", required: false, default: "/placeholder.png" }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false, default: "placeholder" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["category"] }
  - name: "other"
    label: "Andere"
    folder: "src/other"
    create: true
    slug: "{{titel}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Bild", name: "image", widget: "image", required: false, default: "/placeholder.png" }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false, default: "placeholder" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
